### ISSUE TITLE
Commercial Invoice v1 Checklist

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#866]
- [ ]  Realistic JSON example
- [ ] JSON-LD term confirmed
- [ ] Top level shape of the JSON schema (issuanceData, issuer, etc) confirmed
- [ ] On credential schemas (/credentials) $linkedData is only defined for the top level rdf type
- [ ] Required properties confirmed
- [ ] Fully inlined the entire schema, no external $refs
