### ISSUE TITLE
Packing List v1 Checklist

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-vocab#867]
- [x]  Realistic JSON example
- [x] JSON-LD term confirmed
- [x] Top level shape of the JSON schema (issuanceData, issuer, etc) confirmed
- [x] On credential schemas (/credentials) $linkedData is only defined for the top level rdf type
- [x] Required properties confirmed
- [x] Fully inlined the entire schema, no external $refs

**Comment by nissimsan** [comment]
Just looked over this, checked all boxes. Closing.
